### ISSUE TITLE
NEMA17 Printed Part not fit

### ISSUE THREAD

**Issue by ghost** [aTinyShellScript/v2.4_AWD#5]
I printed the 17_FrontPlate_x2.stl part, but it doesn't fit the extruder.
Can you fix this?

![image](https://github.com/aTinyShellScript/v2.4_AWD/assets/104955811/d81af378-a77d-4366-a7dd-5230a4d416be)

**Comment by xPakrikx** [comment]
looks like you are using 2020 t-slot but parts are for 2020 v-slot profile.

**Comment by aTinyShellScript** [comment]
I got lazy with the printed parts and used measurements from pieces of extrusion I had lying around. They were a best-effort for someone who asked and aren't really a supported part of the mod. You can edit the profile in the CAD to fit.
