### ISSUE TITLE
2WD needs 4x printed 10mm spacers, not 2x

### ISSUE THREAD

**Issue by louisrousseau** [aTinyShellScript/v2.4_AWD#7]
Documentation should have a note to this effect

**Comment by aTinyShellScript** [comment]
There is a breaking issue with the build pipeline for the docs right now, so this will be updated at some point in the near future.

**Comment by aTinyShellScript** [comment]
Docs site has been updated. 

https://docs.atinyshellscript.com/v2.4/2wd/#printed-parts
