### ISSUE TITLE
M5_M3_Aligner_[x8].stl wrong size ?

### ISSUE THREAD

**Issue by ga73** [aTinyShellScript/v2.4_AWD#9]
Hi, 
the file STLs/NEMA14/MetalPlates/M5_M3_Aligner_[x8].stl 
the part scale seems way off , it's HUGE.
can this be corrected please ?

thanks!

**Comment by aTinyShellScript** [comment]
@ga73 Good catch. It looks like I selected 'cm' instead of 'mm' when fixing the part alignment after export. Should be fixed now.
